edwin:
    edwin_controller:
        type: position_controllers/JointTrajectoryController
        action_ns: "follow_joint_trajectory"
        joints:
            - waist
            - shoulder
            - elbow
            - hand
            - wrist
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

controller_list:
  - name: "edwin/edwin_controller"
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory 
    default: true
    joints:
        - waist
        - shoulder
        - elbow
        - hand
        - wrist
